### ISSUE TITLE
Roadmap: beta-1.0.0

### ISSUE THREAD

**Issue by ewen-lbh** [schoolsyst/frontend#1]
> This is the roadmap for schoolsyst's first "official" release: `beta-1.0.0` !

- [ ] email verification for account registration
- [x] README.md
- [x] debounce more stuff
- [x] get rid of legacy code
- [ ] basics of www.schoolsyst.com
- [x] responsive design *everywhere*
- [ ] allow editing of all objects
    - [ ] subjects @ /settings/
    - [ ] subjects @ /setup/subjects/
    - [x] homework @ /homework/
    - [ ] grades @ /grades/ (is bugged for now)
- [ ] fix accessibility (tab order + enter) in forms
- [x] bug reporting (redirect to github, "bug" issue template)
- [x] notes editor: save to PDF
- [ ] notes editor: table editing
- [x] notes editor: Note title as \<title\>
- [ ] create external-type notes  
- [ ] fix #13 
- [x] hide unfinished pages (eg. /schedule/)
